# Generated by Django 2.1 on 2018-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_auto_20180804_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='madeYear',
            field=models.IntegerField(default=2018, max_length=4),
            preserve_default=False,
        ),
    ]
