# Generated by Django 2.1 on 2018-08-05 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_auto_20180805_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='madeYear',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2999), django.core.validators.MinValueValidator(2000)]),
        ),
    ]
