# Generated by Django 2.1 on 2018-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0007_auto_20180805_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='madeYear',
            field=models.CharField(choices=[('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default=2018, max_length=4),
        ),
    ]
